steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/restapi:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/${PROJECT_ID}/restapi:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'restapi'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--image=gcr.io/${PROJECT_ID}/restapi:$SHORT_SHA'